### ISSUE TITLE
additionalData may not be undefined

### ISSUE THREAD

**Issue by holtwick** [dchest/xaes#1]
In Chromium I got an error message due to missing `additionalData`. This change fixes it:

```js
additionalData: params.additionalData ?? new Uint8Array(),
```

Found it using new vitest Browser Mode ;) 

I cloned this awesome piece of software for convenience in my small JS framework. See details here https://github.com/holtwick/zeed/blob/master/src/common/crypto/xaes.ts#L111

Thanks for the implementation! It is super cool!

**Comment by dchest** [comment]
Thank you! I think the spec on this is ambiguous:

> Let additionalData be [the contents of](https://www.w3.org/TR/WebCryptoAPI/#concept-contents-of-arraybuffer) the [additionalData](https://www.w3.org/TR/WebCryptoAPI/#dfn-AesGcmParams-additionalData) member of normalizedAlgorithm if present or the empty octet string otherwise.

It says "if present", not "if undefined", so Chrome seems to be correct here, however it doesn't say to throw an error (although I guess this is assumed by IDL having BufferSource type?). Node accepts `undefined`, while Safari accept `undefined` and `null`.

I was tempted to fix it a bit differently (only add `additionalData` to GCM params if it's present in the given params) for two reasons:

1. so that the exception is passed to the user of the library;
2. for "purity": some cryptographic algorithms have distinction between zero-length data and missing data (although this is not the case for GCM, and the WebCrypto spec says to set it to the empty octet string anyway).

However, seeing that different runtimes interpret the spec differently and how I was caught by it — screw this! — I've adopted your solution to normalize the behavior by passing the empty additionalData.
